### ISSUE TITLE
Working with NextJS

### ISSUE THREAD

**Issue by YoannDelpierre** [marvelapp/react-ab-test#12]
Hey,

I'm looking how to I can use this wonderfull package with NextJS and especially with SSR.

I'm using `userIdentifier` like you said, but if I force the local value to A test, it renders B test and update the local value to B value instead of keeping A value.

Any idea how I can manage this ?

Thanks

**Comment by moretti** [comment]
Hi @YoannDelpierre, did you find a solution to this problem?

**Comment by YoannDelpierre** [comment]
Hi @moretti , yes it's ok. I misunderstood how it works form react-ab-test point of view.

It's totally cool right now.

Thanks

**Comment by lpanjwani** [comment]
@YoannDelpierre Could you share how you overcame this issue?

**Comment by joselevelsup** [comment]
@YoannDelpierre Yeah, can you please share how you solved this issue? I am having the same issue using `userIdentifier`. Thanks!

**Comment by YoannDelpierre** [comment]
@joselevelsup @lpanjwani Nothing special, I just put the userIdentifier as props in Experiment component

```tsx
<Experiment name={EXPERIMENT_RANGE_NAME} userIdentifier={userId}>
<Variant name={EXPERIMENT_RANGE_VARIATIONS.WITH}>xxx</VARIANT>
<Variant name={EXPERIMENT_RANGE_VARIATIONS.WITHOUT}>yyy</VARIANT>
</Experiment>
```

And I used

```tsx
useEffect(() => {
    emitter.defineVariants(EXPERIMENT_RANGE_NAME, [
      EXPERIMENT_RANGE_VARIATIONS.WITH,
      EXPERIMENT_RANGE_VARIATIONS.WITHOUT
    ]);
    emitter.calculateActiveVariant(EXPERIMENT_RANGE_NAME);
}, [])
```
