### ISSUE TITLE
[FEATURE] Enable DebuggerPanel in Production

### ISSUE THREAD

**Issue by philals** [marvelapp/react-ab-test#3]
Hi @moretti Thanks for forking and getting this working with React 16! I'm using your package.

I have opened an issue here: https://github.com/pushtell/react-ab-test/issues/49

Wondering if you want this in your fork? I don't think it will gain much traction in the base repo due to in activity.

**Comment by jalopez** [comment]
I've just open a PR to solve this issue: https://github.com/marvelapp/react-ab-test/pull/5

**Comment by moretti** [comment]
Released in `v2.2.0`

Thank you! 🎉
